### ISSUE TITLE
Thank you very much for all the effort you are doing!

### ISSUE THREAD

**Issue by joeydash** [kishanrajput23/NPTEL-The-Joy-of-Computing-using-Python#1]
It would really be great if you add assignment answers also. solutions for multiple-choice questions too.

**Comment by kishanrajput23** [comment]
I already added brother please check all weeks readme file I've already updated readme files

**Comment by thefamousfiveofficial** [comment]
@kishanrajput23 Thanks a lot for your efforts sir.

**Comment by kishanrajput23** [comment]
@thefamousfiveofficial welcome bro. If you like my work then do share with your friends. 👍
