### ISSUE TITLE
Dynamic Week Preview

### ISSUE THREAD

**Issue by Lakhankumawat** [kishanrajput23/NPTEL-The-Joy-of-Computing-using-Python#3]
Although this need not to be an issue 
> Well i had few doubts 
- After this year make someone else as collaborator of this repo so he can change it's week assignments and quizes contents
- Since there is no official good repo i found for same [`Joy of computing using python`] 
- You can manage someone next year who can do this 

**OR**
- I m studying in NIT Patna currently and here we have a system like students have to definitely get some course from nptel and i m sure i will get someone who take this course next year contact me i will try to manage if you wish so

**AlSO**
- Lecture content will probably not change so the source code for lecture programmes will remain same

**Comment by kishanrajput23** [comment]
Thank you for asking brother.
But, no need to worry about that because I'll be updating contents in this repo consistently after this year also.
So, that I can help as many students as I can.

**Comment by Lakhankumawat** [comment]
> Thank you for asking brother.
> But, no need to worry about that because I'll be updating contents in this repo consistently after this year also.
> So, that I can help as many students as I can.

Sounds Great 👍
